### PR TITLE
Mark as release v1.0.7

### PR DESCRIPTION
**Pull request by portante**
Can we consider releasing the latest updates as 1.0.7?

### CODE REVIEW

**Comment by realneel** [comment]
Yeah we can do that! Thanks for the initiative

**Comment by portante** [comment]
@realneel, would you also be able to push the "git hub release" button to make an official release tar ball?

**Comment by realneel** [comment]
i think i did that. Can you please verify?

**Comment by portante** [comment]
Yes, thanks, I posted too early.

**Pull request merged**
