### PR TITLE
Initial Draft of Architecture.md

### PR DESCRIPTION
**Pull request by mrbojangles3**
@realneel ,
This is a draft PR of Architecutre.md. The inspiration for this is from [this](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) blog article. I am also looking to learn more about the project and one way to do that is try to write documentation about the project and fix bugs. The descriptions for the files might be too brief or out right wrong, but I am happy to make corrections. 
If you agree and direct, I can can more info on relevant data structures. I also plan on doing a short run of uperf to generate a flame graph and include it in this file. 
I am happy to discuss this further and welcome any feedback.

### CODE REVIEW

**Comment by realneel** [comment]
Thanks @mrbojangles3 . I will take a look this week. I think it is a good start.

**Comment by realneel** [comment]
Sorry for the delay. This is a great start. One of the things you could also write is a use case focused view on how to extend uperf. How do we add new protocols? How to support more flowops etc..

**Comment by mrbojangles3** [comment]
No worries on the delay, thank you for the feedback. One thing I have been thinking of proposing is a 'lookup' flow op. Where the flowop does a `gethostbyname` call. I will give that a look and update the draft.

**Comment by mrbojangles3** [comment]
I browsed around and found the `design_notes.txt` file which has good content for this document. I can bring the contents of that document into this file if that is acceptable?

**Comment by mrbojangles3** [comment]
Still working on this, I am on a leave at the moment. I expect work to resume in early August.

**Comment by mrbojangles3** [comment]
@realneel I think this is a good amount of content for the file until I learn more things that should be added. I admit that I didn't find the design_notes.txt file until I started this process, and much of what is added here is taken from that file. Do you still think this is a worthwhile addition to the project? Or perhaps the `design_notes.txt` file could be more prominently featured to make it easier for others to find?

**Comment by realneel** [comment]
Thanks this actually looks like a good start. We can expand over time. A few other things that might be useful (in the future perhaps) are

1. You mentioned a `lookup` flowop. Maybe you can write a tutorial style doc on how to add support for a new flowop?
2. Adding support for a new protocol
3. I am not a big fan of the use of "master/slave". We should perhaps consider renaming them.

**Comment by realneel** [comment]
One minor change - Can you please put a pointer to the architecture in the manual ?

**Comment by mrbojangles3** [comment]
I am planning on a followup commit for the `lookup` flowop. If it agreeable, I would like to try for a one commit for the code, docs, and test, so we can update the Architecture.md with a link to the commit so people can see what would need to change.
I don't have a new protocol in mind to add to uperf, but I agree that the process should be added to the docs.

As for replacing the master / slave terminology I have seen the following as suggested replacements.  

- primary / secondary
- source / replica
- initiator, requester / responder
- controller, host / device, worker, proxy
- director / performer
To me, initiator / responder seem to fit the best. What do you think?

**Comment by realneel** [comment]
yeah those are some good terms to consider. I suggest we check in the architecture doc for now and plan on separate commits for the future work.

**Comment by mrbojangles3** [comment]
I've marked the PR as ready for review, but the CI check failed for what looks like autotools related reasons. I am still learning autoconf. Is this something that I should change in the CI? maybe a `autoupdate` call, if appropriate?

**Review by realneel — APPROVED** [review]
LGTM

**Comment by realneel** [comment]
This is the automake error. Maybe @stefano-garzarella has an idea whats wrong?
```
configure.ac:12: error: version mismatch.  This is Automake 1.16.1,
configure.ac:12: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:12: comes from Automake 1.16.2.  You should recreate
configure.ac:12: aclocal.m4 with aclocal and run automake again.
```

**Comment by realneel** [comment]
@mrbojangles3 can you please rebase? I pushed the fix by Stefano to master

**Pull request merged**
