### PR TITLE
Example code to add a flowop

### PR DESCRIPTION
**Pull request by mrbojangles3**
This PR serves as documentation to to aid a developer in create a new flowop inside of uperf. This flowop causes a DNS request to be sent to the DNS server that the host system is configured to use.

### CODE REVIEW

**Comment by realneel** [comment]
@mrbojangles3 if the primary node does a "LOOKUP", what is the translation for the follower node? For example, if primary does a `write`, the follower does a `read`

**Comment by realneel** [comment]
see https://github.com/uperf/uperf/blob/master/src/flowops.c#L72

**Comment by mrbojangles3** [comment]
I see. okay I had the wrong concept for my lookup flow op. my lookup idea might not be as applicable as I thought. Perhaps I should think more about an example flowop.

**Comment by mrbojangles3** [comment]
Apologies for leaving this open.

**Pull request closed without merging**
